name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - toolz
  - psutils
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - pip:
    - git+https://github.com/blaze/dask.git#egg=dask[complete]
